/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jewelary;

import java.awt.Color;
import java.awt.Font;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
/**
 *
 * @author sakib
 */
public class BookProduct extends javax.swing.JFrame {

    /**
     * Creates new form BookProduct
     */
	public BookProduct a=null;
	
	public void setob(BookProduct b){
		this.a=b;
	}
	
    public BookProduct() {
    	this.setResizable(true);
        initComponents();
        GoldTxt.setText("0.0");
        StoneTxt.setText("0.0");
        ChangeTxt.setText("0.0");
        VatTxt.setText("0.0");
        TotalTxt.setText("0.0");
        PaidTxt.setText("0.0");
        DueTxt.setText("0.0");
        currectdata();
        gettransandcid();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        TransectionIDTxt.setEditable(false);		// -mm
        TransectionIDTxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        TransectionIDTxt.setBackground(Color.LIGHT_GRAY);
//        TransectionIDTxt.setBackground(new Color(190, 174, 173));
        setTitle("Book Product");
        this.setLocationRelativeTo(null);
    }
    
    public void currectdata(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH)+1;
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        DateTxt.setText(day+"/"+month+"/"+year);
    }
    public void gettransandcid(){
    	DBManager db=new DBManager();
    	int trans=db.getTidIntDB_2();
    	String trans1=Integer.toString(trans);
    	trans1='T'+trans1;
    	this.TransectionIDTxt.setText(trans1);
    	int cust_id=db.getCidIntDB_2();
    	String cust_id1=Integer.toString(cust_id);
    	cust_id1='C'+cust_id1;
    	this.CustomerIDTxt2.setText(cust_id1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	try {
    		URL iconurl = getClass().getResource("res/Icon_Main.png");
    		ImageIcon icon = new ImageIcon(iconurl);
    		this.setIconImage(icon.getImage());
		} catch (Exception e) {
		}
    	
        jPanel1 = new javax.swing.JPanel();
        BookProductLabel = new javax.swing.JLabel();
        CustomertxtMain = new javax.swing.JTextField();
        CustomerIDmain = new javax.swing.JLabel();
        SearchButton2 = new javax.swing.JButton();
        TransectionIdlabel = new javax.swing.JLabel();
        TransectionIDTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        GoldTxt = new javax.swing.JTextField();
        GoldLabel = new javax.swing.JLabel();
        StoneTxt = new javax.swing.JTextField();
        StoneLabel = new javax.swing.JLabel();
        ChangeTxt = new javax.swing.JTextField();
        ChangeLabel = new javax.swing.JLabel();
        VatTxt = new javax.swing.JTextField();
        VatLabel = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        TotalLabel = new javax.swing.JLabel();
        DueTxt = new javax.swing.JTextField();
        DueTxt.setEditable(false);							// -mm
        DueTxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        DueTxt.setBackground(Color.LIGHT_GRAY);
        PaidTxt = new javax.swing.JTextField();
        PaidLabel = new javax.swing.JLabel();
        DueLabel = new javax.swing.JLabel();
        CalculateButon = new javax.swing.JButton();
        bookProductButon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ProductIDLAbel = new javax.swing.JLabel();
        ProductIDLAbel.setVisible(false);
        ProductIDTxt = new javax.swing.JTextField();
        ProductIDTxt.setVisible(false);
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameTxt = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        CustomerIDTxt2 = new javax.swing.JTextField();
        CustomerIDTxt2.setEditable(false);							// -mm
        CustomerIDTxt2.setHorizontalAlignment(JTextField.CENTER);	// -mm
//        CustomerIDTxt2.setBackground(new Color(190, 174, 173));
        CustomerIDTxt2.setBackground(Color.LIGHT_GRAY);
        CustomerIDLabel2 = new javax.swing.JLabel();
        CnameTxt = new javax.swing.JTextField();
        CNameLabel = new javax.swing.JLabel();
        MobileTxt = new javax.swing.JTextField();
        MobileLabel = new javax.swing.JLabel();
        AdresTxt = new javax.swing.JTextField();
        AdresLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
        DateTxt.setEditable(false);							// -mm
        DateTxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        DateTxt.setBackground(Color.LIGHT_GRAY);
//        DateTxt.setBackground(new Color(190, 174, 173));
//        DateTxt.setFont(new Font("Lucida", Font.BOLD, 18));
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookProductLabel.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        BookProductLabel.setText("Book Product");

        CustomertxtMain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CustomerIDmain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerIDmain.setText("Customer ID:");

        SearchButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchButton2.setText("Search");
        SearchButton2.setPreferredSize(new java.awt.Dimension(100, 23));
        SearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton2ActionPerformed(evt);
            }
        });

        TransectionIdlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TransectionIdlabel.setText("Transaction ID:");

        TransectionIDTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pricing (Per Quantity)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        GoldTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        GoldLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GoldLabel.setText("Gold:");

        StoneTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        StoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StoneLabel.setText("Stone:");

        ChangeTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ChangeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChangeLabel.setText("Charge:");

        VatTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        VatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VatLabel.setText("VAT:");

        TotalTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TotalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalLabel.setText("Total:");

        DueTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PaidTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PaidLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PaidLabel.setText("Paid:");

        DueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DueLabel.setText("Due:");

        CalculateButon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalculateButon.setText("Calculate");
        CalculateButon.setPreferredSize(new java.awt.Dimension(100, 23));
        CalculateButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButonActionPerformed(evt);
            }
        });

        bookProductButon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookProductButon.setText("Book Product");
        bookProductButon.setPreferredSize(new java.awt.Dimension(100, 23));
        bookProductButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookProductButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DueLabel)
                    .addComponent(PaidLabel)
                    .addComponent(TotalLabel)
                    .addComponent(VatLabel)
                    .addComponent(ChangeLabel)
                    .addComponent(StoneLabel)
                    .addComponent(GoldLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(CalculateButon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(bookProductButon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CalculateButon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookProductButon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        ProductIDLAbel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProductIDLAbel.setText("Product ID:");

        ProductIDTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProductNameLabel.setText("Product Name:");

        ProductNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QuantityLabel.setText("Quantity:");

        QuantityTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(QuantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ProductNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ProductIDLAbel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        CustomerIDTxt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CustomerIDLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerIDLabel2.setText("Customer ID:");

        CnameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CNameLabel.setText("Customer Name:");

        MobileTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        MobileLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MobileLabel.setText("Mobile:");

        AdresTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AdresLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdresLabel.setText("Address:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdresLabel)
                    .addComponent(MobileLabel)
                    .addComponent(CNameLabel)
                    .addComponent(CustomerIDLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerIDTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerIDTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Date:");

//        DateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(CustomerIDmain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomertxtMain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TransectionIdlabel)
                        .addGap(18, 18, 18)
                        .addComponent(TransectionIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BookProductLabel)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookProductLabel)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomertxtMain)
                    .addComponent(CustomerIDmain, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransectionIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransectionIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void SearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	ResultSet rs;
    	DBManager db=new DBManager();
    	rs=db.searchCustomerDB(CustomertxtMain.getText());
    	try {
			if(rs.next()){
				CustomerIDTxt2.setText(rs.getString("C_ID"));
				CnameTxt.setText(rs.getString("C_NAME"));
				MobileTxt.setText(rs.getString("C_MOBILE"));
				AdresTxt.setText(rs.getString("C_ADDR"));
				this.CnameTxt.setEditable(false);
				this.CnameTxt.setBackground(Color.LIGHT_GRAY);
				this.MobileTxt.setEditable(false);
				this.MobileTxt.setBackground(Color.LIGHT_GRAY);
				this.AdresTxt.setEditable(false);
				this.AdresTxt.setBackground(Color.LIGHT_GRAY);
			}
		} catch (Exception e) {
		} finally {
			try {
				db.st.close();
				db.conn.close();
			} catch(SQLException sqlex) {
				JOptionPane.showMessageDialog(new JFrame(), sqlex.getClass().getName()+" : "+sqlex.getMessage()+" -mm- DB closing error inside BookProduct!", "Error!", JOptionPane.ERROR_MESSAGE);
			}
		}
    }                                             

    private void CalculateButonActionPerformed(java.awt.event.ActionEvent evt) {    
        // TODO add your handling code here:
    	double gold=Double.parseDouble(GoldTxt.getText());
    	double stone=Double.parseDouble(StoneTxt.getText());
    	double change=Double.parseDouble(ChangeTxt.getText());
    	double total=gold+stone+change;
    	double vat=Double.parseDouble(VatTxt.getText());
    	total=total-(total*(vat/100));
    	TotalTxt.setText(new DecimalFormat("##.##").format(total));
    }                                              

    private void bookProductButonActionPerformed(java.awt.event.ActionEvent evt) {             
        // TODO add your handling code here:
    	double paid=Double.parseDouble(PaidTxt.getText());
    	double total=Double.parseDouble(TotalTxt.getText());
    	double due=total-paid;
    	DueTxt.setText(new DecimalFormat("##.##").format(due));
    	Token tk=new Token(DateTxt.getText(),ProductNameTxt.getText(),ProductIDTxt.getText(),QuantityTxt.getText(),TransectionIDTxt.getText(),CustomerIDTxt2.getText(), CnameTxt.getText(), MobileTxt.getText(), AdresTxt.getText(), Double.parseDouble(GoldTxt.getText()), Double.parseDouble(StoneTxt.getText()), Double.parseDouble(ChangeTxt.getText()), Double.parseDouble(VatTxt.getText()), Double.parseDouble(TotalTxt.getText()), Double.parseDouble(PaidTxt.getText()), Double.parseDouble(DueTxt.getText()),2,a);
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel AdresLabel;
    private javax.swing.JTextField AdresTxt;
    private javax.swing.JLabel BookProductLabel;
    private javax.swing.JLabel CNameLabel;
    private javax.swing.JButton CalculateButon;
    private javax.swing.JLabel ChangeLabel;
    private javax.swing.JTextField ChangeTxt;
    private javax.swing.JTextField CnameTxt;
    private javax.swing.JLabel CustomerIDLabel2;
    private javax.swing.JTextField CustomerIDTxt2;
    private javax.swing.JLabel CustomerIDmain;
    private javax.swing.JTextField CustomertxtMain;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JLabel DueLabel;
    private javax.swing.JTextField DueTxt;
    private javax.swing.JLabel GoldLabel;
    private javax.swing.JTextField GoldTxt;
    private javax.swing.JLabel MobileLabel;
    private javax.swing.JTextField MobileTxt;
    private javax.swing.JLabel PaidLabel;
    private javax.swing.JTextField PaidTxt;
    private javax.swing.JLabel ProductIDLAbel;
    private javax.swing.JTextField ProductIDTxt;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTxt;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTxt;
    private javax.swing.JButton SearchButton2;
    private javax.swing.JLabel StoneLabel;
    private javax.swing.JTextField StoneTxt;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JTextField TransectionIDTxt;
    private javax.swing.JLabel TransectionIdlabel;
    private javax.swing.JLabel VatLabel;
    private javax.swing.JTextField VatTxt;
    private javax.swing.JButton bookProductButon;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration                   
}
