/*
 * To Charge this license header, choose License Headers in Project Properties.
 * To Charge this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jewelary;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author sakib
 */
public class CompletePayment extends javax.swing.JFrame {

    /**
     * Creates new form CompletePayment1
     */
    public CompletePayment() {
        initComponents();
        this.setLocationRelativeTo(null);
        currectdata();
//        FinalPaymenttxt.setText("0.0");
        GoldTxt.setEditable(false);
        GoldTxt.setBackground(Color.LIGHT_GRAY);
        StoneTxt.setEditable(false);
        StoneTxt.setBackground(Color.LIGHT_GRAY);
        ChargeTxt.setEditable(false);
        ChargeTxt.setBackground(Color.LIGHT_GRAY);
        VatTxt.setEditable(false);
        VatTxt.setBackground(Color.LIGHT_GRAY);
        TotalTxt.setEditable(false);
        TotalTxt.setBackground(Color.LIGHT_GRAY);
        DueTxt.setEditable(false);
        DueTxt.setBackground(Color.LIGHT_GRAY);
        PaidTxtFinal.setEditable(false);
        ProductIDTxt.setEditable(false);
        ProductIDTxt.setBackground(Color.LIGHT_GRAY);
        ProductNameTxt.setEditable(false);
        ProductNameTxt.setBackground(Color.LIGHT_GRAY);
        QuantityTxt.setEditable(false);
        QuantityTxt.setBackground(Color.LIGHT_GRAY);
        customerIDTxt.setEditable(false);
        customerIDTxt.setBackground(Color.LIGHT_GRAY);
        customerNameTxt.setEditable(false);
        customerNameTxt.setBackground(Color.LIGHT_GRAY);
        MobileTxt.setEditable(false);
        MobileTxt.setBackground(Color.LIGHT_GRAY);
        AdresTxt.setEditable(false);
        AdresTxt.setBackground(Color.LIGHT_GRAY);
        BookingDateTxt.setEditable(false);
        BookingDateTxt.setBackground(Color.LIGHT_GRAY);
        DateTxt.setEditable(false);
        DateTxt.setHorizontalAlignment(JTextField.CENTER);
        DateTxt.setBackground(Color.LIGHT_GRAY);
//        DateTxt.setFont(new Font("Lucida", Font.BOLD, 18));
//        DateTxt.setBackground(new Color(190, 174, 173));
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // -edited by -mm-
        this.setResizable(true);
        setTitle("Complete Due Payment");
    }
    
    public void currectdata(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH)+1;
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        DateTxt.setText(day+"/"+month+"/"+year);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	try {
    		URL iconurl = getClass().getResource("res/Icon_Main.png");
    		ImageIcon icon = new ImageIcon(iconurl);
    		this.setIconImage(icon.getImage());
		} catch (Exception e) {
		}
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        GoldTxt = new javax.swing.JTextField();
        GoldLabel = new javax.swing.JLabel();
        StoneTxt = new javax.swing.JTextField();
        StoneLabel = new javax.swing.JLabel();
        ChargeTxt = new javax.swing.JTextField();
        ChargeLabel = new javax.swing.JLabel();
        VatTxt = new javax.swing.JTextField();
        VatLabel = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        TotalLabel = new javax.swing.JLabel();
        DueTxt = new javax.swing.JTextField();
        DueTxt.setHorizontalAlignment(JTextField.CENTER);			// -mm
        PaidTxtFinal = new javax.swing.JTextField();
        PaidTxtFinal.setHorizontalAlignment(JTextField.CENTER);		// -mm
        PaidTxtFinal.setBackground(Color.LIGHT_GRAY);
        PaidLabelFinal = new javax.swing.JLabel();
        DueLabel = new javax.swing.JLabel();
        FinalPaymenttxt = new javax.swing.JTextField();
        PaidLabel = new javax.swing.JLabel();
        RecievePayButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ProductIDLabel = new javax.swing.JLabel();
        ProductIDLabel.setVisible(false);
        ProductIDTxt = new javax.swing.JTextField();
        ProductIDTxt.setVisible(false);
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameTxt = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        customerIDTxt = new javax.swing.JTextField();
        customerIDLabel = new javax.swing.JLabel();
        customerNameTxt = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        MobileTxt = new javax.swing.JTextField();
        MobileLabel = new javax.swing.JLabel();
        AdresTxt = new javax.swing.JTextField();
        AdresLabel = new javax.swing.JLabel();
        BookingDateTxt = new javax.swing.JTextField();
        BookingDateLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        TransectionIDLabel = new javax.swing.JLabel();
        TransectionIDTxt = new javax.swing.JTextField();
        DateTxt = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pricing (Per Quantity)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        GoldTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        GoldLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GoldLabel.setText("Gold:");

        StoneTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        StoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StoneLabel.setText("Stone:");

        ChargeTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ChargeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChargeLabel.setText("Charge:");

        VatTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        VatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VatLabel.setText("VAT:");

        TotalTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TotalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalLabel.setText("Total:");

        DueTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PaidTxtFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PaidLabelFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PaidLabelFinal.setText("Paid:");

        DueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DueLabel.setText("Due:");

        FinalPaymenttxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PaidLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PaidLabel.setText("Pay:");

        RecievePayButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RecievePayButton.setText("OK");
        f=new File("src/jewelary/res/Payment_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		RecievePayButton.setIcon(i);
		}
		catch(Exception e){
			
		}
        RecievePayButton.setPreferredSize(new java.awt.Dimension(100, 23));
        RecievePayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecievePayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DueLabel)
                            .addComponent(PaidLabelFinal)
                            .addComponent(TotalLabel)
                            .addComponent(VatLabel)
                            .addComponent(ChargeLabel)
                            .addComponent(StoneLabel)
                            .addComponent(GoldLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaidTxtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PaidLabel)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RecievePayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FinalPaymenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinalPaymenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RecievePayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaidTxtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaidLabelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        ProductIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProductIDLabel.setText("Product ID:");

        ProductIDTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProductNameLabel.setText("Product Name:");

        ProductNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QuantityLabel.setText("Quantity:");

        QuantityTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(QuantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ProductNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ProductIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        customerIDTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        customerIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerIDLabel.setText("Customer ID:");

        customerNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CustomerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerNameLabel.setText("Customer Name:");

        MobileTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        MobileLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MobileLabel.setText("Mobile:");

        AdresTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AdresLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdresLabel.setText("Address:");

        BookingDateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BookingDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookingDateLabel.setText("Booking Date:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BookingDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BookingDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdresLabel)
                            .addComponent(MobileLabel)
                            .addComponent(CustomerNameLabel)
                            .addComponent(customerIDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchButton.setText("Search");
    	f=new File("src/jewelary/res/Search_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		SearchButton.setIcon(i);
		}
		catch(Exception e){
			
		}
        SearchButton.setPreferredSize(new java.awt.Dimension(100, 23));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        TransectionIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TransectionIDLabel.setText("Transaction ID:");

        TransectionIDTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

//        DateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateLabel.setText("Date:");

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 25)); // NOI18N
        jLabel8.setText("Complete Due Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(162, 162, 162)
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(TransectionIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TransectionIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransectionIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransectionIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
                                         

    /**
     * @param args the command line arguments
     */

    private void RecievePayButtonActionPerformed(java.awt.event.ActionEvent evt) {    
        // TODO add your handling code here:
    	try{
    		int yes = JOptionPane.showConfirmDialog(null, "Recieved FULL payment?", "Confirmation", JOptionPane.YES_NO_OPTION);
			if(yes == JOptionPane.YES_OPTION) {
	    		double pf=Double.parseDouble(PaidTxtFinal.getText());
	        	double p=Double.parseDouble(FinalPaymenttxt.getText());
	        	pf=pf+p;
	        	double due=Double.parseDouble(DueTxt.getText());
	        	due=due-p;
	        	DueTxt.setText(new DecimalFormat("##.##").format(due));
	        	PaidTxtFinal.setText(new DecimalFormat("##.##").format(pf));
	    		DBManager db=new DBManager();
	        	db.completePaymentDB(DateTxt.getText(), TransectionIDTxt.getText(), pf);
			}
    	}catch(Exception e){
    		JOptionPane.showMessageDialog(new JFrame(), "Check Input!", "Error!", JOptionPane.ERROR_MESSAGE);
    	}
    	
    }                                                

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	ResultSet rs;
    	DBManager db=new DBManager();
    	rs=db.searchTidComPayDB(TransectionIDTxt.getText());
    	try {
    		int quan=0;
    		double tot=0;
    		double paid=0;
    		double due=0;
			while(rs.next()){
				quan++;
				MobileTxt.setText(rs.getString("C_MOBILE"));
				AdresTxt.setText(rs.getString("C_ADDR"));
				customerIDTxt.setText(rs.getString("C_ID"));
				customerNameTxt.setText(rs.getString("C_NAME"));
				BookingDateTxt.setText(rs.getString("DATE_BOOKING"));
				ProductIDTxt.setText(rs.getString("P_ID"));
				ProductNameTxt.setText(rs.getString("P_NAME"));
				tot+=Double.parseDouble(rs.getString("SELLING_PRICE"));
				paid+=Double.parseDouble(rs.getString("PAID"));
				due+=Double.parseDouble(rs.getString("DUE"));
				GoldTxt.setText(rs.getString("GOLD"));
				StoneTxt.setText(rs.getString("STONE"));
				ChargeTxt.setText(rs.getString("CHARGE"));
				VatTxt.setText(rs.getString("VAT"));
			}
			QuantityTxt.setText(Integer.toString(quan));
			TotalTxt.setText(Double.toString(tot));
			DueTxt.setText(Double.toString(due));
			PaidTxtFinal.setText(Double.toString(paid));
			
		} catch (Exception e) {
		} finally {
			try {
				db.st.close();
				db.conn.close();
			} catch(SQLException sqlex) {
				JOptionPane.showMessageDialog(new JFrame(), sqlex.getClass().getName()+" : "+sqlex.getMessage()+" -mm- DB closing error!", "Error!", JOptionPane.ERROR_MESSAGE);
			}
		}
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompletePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel AdresLabel;
    private javax.swing.JTextField AdresTxt;
    private javax.swing.JLabel BookingDateLabel;
    private javax.swing.JTextField BookingDateTxt;
    private javax.swing.JLabel ChargeLabel;
    private javax.swing.JTextField ChargeTxt;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JLabel DueLabel;
    private javax.swing.JTextField DueTxt;
    private javax.swing.JLabel GoldLabel;
    private javax.swing.JTextField GoldTxt;
    private javax.swing.JLabel MobileLabel;
    private javax.swing.JTextField MobileTxt;
    private javax.swing.JLabel PaidLabel;
    private javax.swing.JLabel PaidLabelFinal;
    private javax.swing.JTextField FinalPaymenttxt;
    private javax.swing.JTextField PaidTxtFinal;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductIDTxt;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTxt;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTxt;
    private javax.swing.JButton RecievePayButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel StoneLabel;
    private javax.swing.JTextField StoneTxt;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel TransectionIDLabel;
    private javax.swing.JTextField TransectionIDTxt;
    private javax.swing.JLabel VatLabel;
    private javax.swing.JTextField VatTxt;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerIDTxt;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    Image image;
    File f;
    // End of variables declaration                   
}
