/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jewelary;
import java.io.*;
import java.net.URL;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Sourav
 */
public class Exchange extends javax.swing.JFrame {

    /**
     * Creates new form Exchange
     */
	
	public Exchange a=null;
	
	public void setob(Exchange b){
		this.a=b;
	}
	
    public Exchange() {
    	this.setResizable(true);
        initComponents();
        this.ProductIDLabel.setVisible(false);
        this.ProductIDTxt.setVisible(false);
        OldGoldTxt.setText("0.0");
        NewGoldTxt.setText("0.0");
        BalanceTxt.setText("0.0");
        setLocationRelativeTo(null);
        setTitle("Exchange");
        currectdata();
        gettransandcid();
        this.ExchangeDateLabel.setVisible(false);
        this.ExchangeDateTxt.setVisible(false);
    }
    
    public void currectdata(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH)+1;
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        DateTxt.setText(day+"/"+month+"/"+year);
    }
    
    public void gettransandcid(){
    	DBManager db=new DBManager();
    	int trans=db.getTidIntDB_2();
    	String trans1=Integer.toString(trans);
    	trans1='T'+trans1;
    	TransIDTxt.setText(trans1);
    	int cust_id=db.getCidIntDB_2();
    	String cust_id1=Integer.toString(cust_id);
    	cust_id1='C'+cust_id1;
    	CustomerIDtxt.setText(cust_id1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        try {
    		URL iconurl = getClass().getResource("res/Icon_Main.png");
    		ImageIcon icon = new ImageIcon(iconurl);
    		this.setIconImage(icon.getImage());
		} catch (Exception e) {
		}
        
        FrontPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerIDmainLabel = new javax.swing.JLabel();
        CustomerIDmainTxt = new javax.swing.JTextField();
        SearchBut = new javax.swing.JButton();
    	f=new File("src/jewelary/res/Search_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		SearchBut.setIcon(i);
		}
		catch(Exception e){
			
		}
        MobileNolabel = new javax.swing.JLabel();
        CustomerInfolabel = new javax.swing.JLabel();
        CustomerIDlabel = new javax.swing.JLabel();
        Addrslabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CustomerIDtxt = new javax.swing.JTextField();
        CustomerIDtxt.setEditable(false); 				// -mm
        CustomerIDtxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        CustomerIDtxt.setBackground(Color.LIGHT_GRAY);
        MobileNoTxt = new javax.swing.JTextField();
        Adrestxt = new javax.swing.JTextField();
        CustomerNamelabel = new javax.swing.JLabel();
        CustomerNametxt = new javax.swing.JTextField();
        ExchangeDateLabel = new javax.swing.JLabel();
        ExchangeDateTxt = new javax.swing.JTextField();
        ProductPanel = new javax.swing.JPanel();
        TransIdLabel = new javax.swing.JLabel();
        TransIDTxt = new javax.swing.JTextField();
        TransIDTxt.setEditable(false); 					// -mm
        TransIDTxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        TransIDTxt.setBackground(Color.LIGHT_GRAY);
        QuantityLabel = new javax.swing.JLabel();
        ProductIDLabel = new javax.swing.JLabel();
        ProductInfoLabel = new javax.swing.JLabel();
        ProductIDTxt = new javax.swing.JTextField();
        ProductNameTxt = new javax.swing.JTextField();
        OldGoldTxt = new javax.swing.JTextField();
        ProductNameLabel = new javax.swing.JLabel();
        OkBut = new javax.swing.JButton();
    
    	f=new File("src/jewelary/res/Tick_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		OkBut.setIcon(i);
		}
		catch(Exception e){
			
		}
        OldGoldPurchaseLabel = new javax.swing.JLabel();
        QuantityTxt1 = new javax.swing.JTextField();
        NewGoldSellLabel = new javax.swing.JLabel();
        NewGoldTxt = new javax.swing.JTextField();
        BalanceLabel = new javax.swing.JLabel();
        BalanceTxt = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
        DateTxt.setEditable(false); 			// -mm
        DateTxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        DateTxt.setBackground(Color.LIGHT_GRAY);
//        DateTxt.setBackground(new Color(190, 174, 173));
//        DateTxt.setFont(new Font("Lucida", Font.BOLD, 18));
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FrontPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("Exchange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 300, 0, 0);
        FrontPanel.add(jLabel1, gridBagConstraints);

        CustomerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CustomerPanel.setLayout(new java.awt.GridBagLayout());

        CustomerIDmainLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerIDmainLabel.setText("Customer ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 0);
        CustomerPanel.add(CustomerIDmainLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        CustomerPanel.add(CustomerIDmainTxt, gridBagConstraints);

        SearchBut.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 2);
        CustomerPanel.add(SearchBut, gridBagConstraints);

        MobileNolabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MobileNolabel.setText("Mobile No:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        CustomerPanel.add(MobileNolabel, gridBagConstraints);

        CustomerInfolabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CustomerInfolabel.setText("Customer Info:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        CustomerPanel.add(CustomerInfolabel, gridBagConstraints);

        CustomerIDlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerIDlabel.setText("Customer ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        CustomerPanel.add(CustomerIDlabel, gridBagConstraints);

        Addrslabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addrslabel.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        CustomerPanel.add(Addrslabel, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 248, 0);
        CustomerPanel.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 5, 0, 0);
        CustomerPanel.add(CustomerIDtxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 5, 0, 0);
        CustomerPanel.add(MobileNoTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 5, 0, 0);
        CustomerPanel.add(Adrestxt, gridBagConstraints);

        CustomerNamelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerNamelabel.setText("Customer Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        CustomerPanel.add(CustomerNamelabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 5, 0, 0);
        CustomerPanel.add(CustomerNametxt, gridBagConstraints);

        ExchangeDateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExchangeDateLabel.setText("Exchange Date :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 248, 0);
        CustomerPanel.add(ExchangeDateLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 5, 0, 0);
        CustomerPanel.add(ExchangeDateTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(75, 0, 11, 0);
        FrontPanel.add(CustomerPanel, gridBagConstraints);

        ProductPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TransIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TransIdLabel.setText("Transaction ID:");

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuantityLabel.setText("Quantity:");

        ProductIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductIDLabel.setText("Product ID:");

        ProductInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProductInfoLabel.setText("Product Info:");

        ProductNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductNameLabel.setText("Product Name:");

        OkBut.setText("OK");
        OkBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButActionPerformed(evt);
            }
        });
        this.SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        OldGoldPurchaseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OldGoldPurchaseLabel.setText("Old Gold Purchase :");

        QuantityTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTxt1ActionPerformed(evt);
            }
        });

        NewGoldSellLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewGoldSellLabel.setText("New Gold Sell :");

        BalanceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BalanceLabel.setText("Balance :");

        DateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateLabel.setText("Date :");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductInfoLabel))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(OkBut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(NewGoldSellLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NewGoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(BalanceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(OldGoldPurchaseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(OldGoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                .addComponent(QuantityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QuantityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                .addComponent(ProductIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                .addComponent(ProductNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(TransIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TransIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TransIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(ProductInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldGoldPurchaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OldGoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewGoldSellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewGoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(OkBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(75, 6, 11, 10);
        FrontPanel.add(ProductPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrontPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrontPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void QuantityTxt1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       
    }                                            

    private void OkButActionPerformed(java.awt.event.ActionEvent evt) {   
    	double balance;
    	double oldPurchase=Double.parseDouble(this.OldGoldTxt.getText());
    	double newSell=Double.parseDouble(this.NewGoldTxt.getText());
    	balance=newSell-oldPurchase;
    	this.BalanceTxt.setText(Double.toString(balance));
    	new Token(this.DateTxt.getText(),this.TransIDTxt.getText(),this.ProductNameTxt.getText(),this.ProductIDTxt.getText(),this.QuantityTxt1.getText(),this.CustomerIDtxt.getText(),this.CustomerNametxt.getText(),this.MobileNoTxt.getText(),this.Adrestxt.getText(),balance,4,a);
    			
    } 	
                                
   
    public void  searchButtonActionPerformed(java.awt.event.ActionEvent evt){
	   	ResultSet rs;
    	DBManager db=new DBManager();
    	rs=db.searchCustomerDB(this.CustomerIDmainTxt.getText());
    	try {
			if(rs.next()){
				this.CustomerIDtxt.setText(rs.getString("C_ID"));
				this.CustomerNametxt.setText(rs.getString("C_NAME"));
				this.MobileNoTxt.setText(rs.getString("C_MOBILE"));
				this.Adrestxt.setText(rs.getString("C_ADDR"));
				this.CustomerNametxt.setEditable(false);
				this.CustomerNametxt.setBackground(Color.LIGHT_GRAY);
				this.MobileNoTxt.setEditable(false);
				this.MobileNoTxt.setBackground(Color.LIGHT_GRAY);
				this.Adrestxt.setEditable(false);
				this.Adrestxt.setBackground(Color.LIGHT_GRAY);
			}
		} catch (Exception e) {
		} finally {
			try {
				db.st.close();
				db.conn.close();
			} catch(Exception sqlex) {
				//JOptionPane.showMessageDialog(new JFrame(), sqlex.getClass().getName()+" : "+sqlex.getMessage()+" -mm- DB closing error!", "Error!", JOptionPane.ERROR_MESSAGE);
			}
		}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Addrslabel;
    private javax.swing.JTextField Adrestxt;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JTextField BalanceTxt;
    private javax.swing.JLabel CustomerIDmainLabel;
    private javax.swing.JTextField CustomerIDmainTxt;
    private javax.swing.JLabel CustomerIDlabel;
    private javax.swing.JTextField CustomerIDtxt;
    private javax.swing.JLabel CustomerInfolabel;
    private javax.swing.JLabel CustomerNamelabel;
    private javax.swing.JTextField CustomerNametxt;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JLabel ExchangeDateLabel;
    private javax.swing.JTextField ExchangeDateTxt;
    private javax.swing.JPanel FrontPanel;
    private javax.swing.JTextField MobileNoTxt;
    private javax.swing.JLabel MobileNolabel;
    private javax.swing.JLabel NewGoldSellLabel;
    private javax.swing.JTextField NewGoldTxt;
    private javax.swing.JButton OkBut;
    private javax.swing.JLabel OldGoldPurchaseLabel;
    private javax.swing.JTextField OldGoldTxt;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductIDTxt;
    private javax.swing.JLabel ProductInfoLabel;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTxt;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTxt1;
    private javax.swing.JButton SearchBut;
    private javax.swing.JTextField TransIDTxt;
    private javax.swing.JLabel TransIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    Image image;
    File f;
    // End of variables declaration                   
}
