/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jewelary;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.net.URL;
import java.sql.ResultSet;
import java.io.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
public class Sell extends javax.swing.JFrame {

    /**
     * Creates new form Exchange
     */
	public Sell a=null;
	
	public void setob(Sell b){
		this.a=b;
	}
	
    public Sell() {
    	this.setResizable(true);
        initComponents();
        this.ProductIDLabel.setVisible(false);
        this.ProductIDTxt.setVisible(false);
        GoldTxt.setText("0.0");
        StoneTxt.setText("0.0");
        ChargeTxt.setText("0.0");
        VatTxt.setText("0.0");
        TotalTxt.setText("0.0");
        currectdata();
        gettransandcid();
        setLocationRelativeTo(null);
        setTitle("Sell Product");
    }
    
    public void currectdata(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH)+1;
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        DateTxt.setText(day+"/"+month+"/"+year);
    }
    
    public void gettransandcid(){
    	DBManager db=new DBManager();
    	int trans=db.getTidIntDB_2();
    	String trans1=Integer.toString(trans);
    	trans1='T'+trans1;
    	TransIDTxt.setText(trans1);
    	int cust_id=db.getCidIntDB_2();
    	String cust_id1=Integer.toString(cust_id);
    	cust_id1='C'+cust_id1;
    	CustomerIDtxt.setText(cust_id1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        try {
    		URL iconurl = getClass().getResource("res/Icon_Main.png");
    		ImageIcon icon = new ImageIcon(iconurl);
    		this.setIconImage(icon.getImage());
		} catch (Exception e) {
		}
        
        FrontPanel = new javax.swing.JPanel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerIDmainLabel = new javax.swing.JLabel();
        CustomerIDmainTxt = new javax.swing.JTextField();
        SearchBut = new javax.swing.JButton();
        MobileNolabel = new javax.swing.JLabel();
        CustomerInfolabel = new javax.swing.JLabel();
        CustomerIDlabel = new javax.swing.JLabel();
        Addrslabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CustomerIDtxt = new javax.swing.JTextField();
        CustomerIDtxt.setEditable(false);				// -mm
        CustomerIDtxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        CustomerIDtxt.setBackground(Color.LIGHT_GRAY);
        MobileNoTxt = new javax.swing.JTextField();
        Adrestxt = new javax.swing.JTextField();
        CustomerNamelabel = new javax.swing.JLabel();
        CustomerNametxt = new javax.swing.JTextField();
        ProductPanel = new javax.swing.JPanel();
        TransIdLabel = new javax.swing.JLabel();
        TransIDTxt = new javax.swing.JTextField();
        TransIDTxt.setEditable(false);				// -mm
        TransIDTxt.setHorizontalAlignment(JTextField.CENTER);	// -mm
        TransIDTxt.setBackground(Color.LIGHT_GRAY);
        QuantityLabel = new javax.swing.JLabel();
        ProductIDLabel = new javax.swing.JLabel();
        ProductInfoLabel = new javax.swing.JLabel();
        ProductIDTxt = new javax.swing.JTextField();
        ProductNameTxt = new javax.swing.JTextField();
        ProductNameLabel = new javax.swing.JLabel();
        QuantityTxt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        GoldLabel = new javax.swing.JLabel();
        StoneLabel = new javax.swing.JLabel();
        ChargeLabel = new javax.swing.JLabel();
        VatLabel = new javax.swing.JLabel();
        CalculateButton = new javax.swing.JButton();
        f=new File("src/jewelary/res/Calculator_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		this.CalculateButton.setIcon(i);
		}
		catch(Exception e){
			System.out.println("noooo");
		}
        TotalLabel = new javax.swing.JLabel();
        SellButton = new javax.swing.JButton();
        f=new File("src/jewelary/res/Tick_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		this.SellButton.setIcon(i);
		}
		catch(Exception e){
			
		}
        GoldTxt = new javax.swing.JTextField();
        StoneTxt = new javax.swing.JTextField();
        ChargeTxt = new javax.swing.JTextField();
        VatTxt = new javax.swing.JTextField();
        TotalTxt = new javax.swing.JTextField();
        TotalTxt.setHorizontalAlignment(JTextField.CENTER);
        DateLabel = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
//        DateTxt.setEditable(false);					// -mm
        DateTxt.setHorizontalAlignment(JTextField.CENTER);	//-mm
//        DateTxt.setFont(new Font("Lucida", Font.BOLD, 18));
//        DateTxt.setBackground(new Color(190, 174, 173));
        DateTxt.setBackground(Color.LIGHT_GRAY);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        CustomerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        CustomerIDmainLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerIDmainLabel.setText("Customer ID:");

        SearchBut.setText("Search");
		
		f=new File("src/jewelary/res/Search_Icon.png");
		try{
		image=ImageIO.read(f);
		ImageIcon i=new ImageIcon(image);
		SearchBut.setIcon(i);
		}
		catch(Exception e){
			
		}

        MobileNolabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MobileNolabel.setText("Mobile No:");

        CustomerInfolabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CustomerInfolabel.setText("Customer Info:");

        CustomerIDlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerIDlabel.setText("Customer ID:");

        Addrslabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addrslabel.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        CustomerNamelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerNamelabel.setText("Customer Name:");

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerIDmainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerIDmainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBut, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(CustomerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerPanelLayout.createSequentialGroup()
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerIDlabel)
                                    .addComponent(MobileNolabel)
                                    .addComponent(Addrslabel))
                                .addGap(28, 28, 28)
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Adrestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MobileNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustomerIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerPanelLayout.createSequentialGroup()
                                .addComponent(CustomerNamelabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CustomerNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CustomerInfolabel, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerIDmainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerIDmainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(CustomerInfolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerIDlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileNolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addrslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adrestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        ProductPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TransIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TransIdLabel.setText("Transaction ID:");

        TransIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransIDTxtActionPerformed(evt);
            }
        });

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuantityLabel.setText("Quantity:");

        ProductIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductIDLabel.setText("Product ID:");

        ProductInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProductInfoLabel.setText("Product Info:");

        ProductNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductNameLabel.setText("Product Name:");

        QuantityTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTxt1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Pricing (per quantity)");

        GoldLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoldLabel.setText("Gold:");

        StoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoneLabel.setText("Stone :");

        ChargeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChargeLabel.setText("Charge :");

        VatLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VatLabel.setText("VAT :");

        CalculateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalLabel.setText("Total :");

        SellButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SellButton.setText("Sell");
        SellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellButtonActionPerformed(evt);
            }
        });
        this.SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        GoldTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldTxtActionPerformed(evt);
            }
        });

        StoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoneTxtActionPerformed(evt);
            }
        });

        ChargeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeTxtActionPerformed(evt);
            }
        });

        VatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VatTxtActionPerformed(evt);
            }
        });

        TotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CalculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(TransIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                .addComponent(VatLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(ChargeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(StoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(GoldLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GoldTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StoneTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ProductInfoLabel)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductIDLabel)
                                    .addComponent(QuantityLabel))
                                .addGap(71, 71, 71)
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuantityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TransIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductNameLabel))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(ProductInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoldLabel)
                    .addComponent(GoldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChargeLabel)
                    .addComponent(ChargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VatLabel)
                    .addComponent(VatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CalculateButton)
                .addGap(18, 18, 18)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(SellButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateLabel.setText("Date :");

        DateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sell");

        javax.swing.GroupLayout FrontPanelLayout = new javax.swing.GroupLayout(FrontPanel);
        FrontPanel.setLayout(FrontPanelLayout);
        FrontPanelLayout.setHorizontalGroup(
            FrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontPanelLayout.createSequentialGroup()
                .addGroup(FrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrontPanelLayout.createSequentialGroup()
                        .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(FrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrontPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FrontPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrontPanelLayout.setVerticalGroup(
            FrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 9);
        getContentPane().add(FrontPanel, gridBagConstraints);
        
        
        CustomerPanel.getRootPane().setDefaultButton(SearchBut);

        pack();
    }// </editor-fold>                        

    private void QuantityTxt1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void DateTxtActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void TransIDTxtActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void GoldTxtActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void StoneTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void ChargeTxtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void VatTxtActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void TotalTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
   	 gold=Double.parseDouble(GoldTxt.getText());
   	 stone=Double.parseDouble(this.StoneTxt.getText());
       charge=Double.parseDouble(this.ChargeTxt.getText());
   	 total=gold+stone+charge;
   	 vat=((Double.parseDouble(this.VatTxt.getText()))/100)*total;
   	total=vat+total;
   	this.TotalTxt.setText(Double.toString(total));
    }                                               

    private void SellButtonActionPerformed(java.awt.event.ActionEvent evt) {   
    	new Token(this.DateTxt.getText(),this.TransIDTxt.getText(),this.ProductNameTxt.getText(),this.ProductIDTxt.getText(),this.CustomerIDtxt.getText(),this.CustomerNametxt.getText(),this.MobileNoTxt.getText(),this.Adrestxt.getText(),gold,stone,charge, vat,total,this.QuantityTxt1.getText(),3,a);
        // TODO add your handling code here:
    }   
   public void  searchButtonActionPerformed(java.awt.event.ActionEvent evt){
	   	ResultSet rs;
    	DBManager db=new DBManager();
    	rs=db.searchCustomerDB(this.CustomerIDmainTxt.getText());
    	try {
			if(rs.next()){
				this.CustomerIDtxt.setText(rs.getString("C_ID"));
				this.CustomerNametxt.setText(rs.getString("C_NAME"));
				this.MobileNoTxt.setText(rs.getString("C_MOBILE"));
				this.Adrestxt.setText(rs.getString("C_ADDR"));
				this.CustomerNametxt.setEditable(false);
				this.CustomerNametxt.setBackground(Color.LIGHT_GRAY);
				this.MobileNoTxt.setEditable(false);
				this.MobileNoTxt.setBackground(Color.LIGHT_GRAY);
				this.Adrestxt.setEditable(false);
				this.Adrestxt.setBackground(Color.LIGHT_GRAY);
			}
		} catch (Exception e) {
		} finally {
			try {
				db.st.close();
				db.conn.close();
			} catch(Exception sqlex) {
				//JOptionPane.showMessageDialog(new JFrame(), sqlex.getClass().getName()+" : "+sqlex.getMessage()+" -mm- DB closing error!", "Error!", JOptionPane.ERROR_MESSAGE);
			}
		}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Addrslabel;
    private javax.swing.JTextField Adrestxt;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel ChargeLabel;
    private javax.swing.JTextField ChargeTxt;
    private javax.swing.JLabel CustomerIDlabel;
    private javax.swing.JLabel CustomerIDmainLabel;
    private javax.swing.JTextField CustomerIDmainTxt;
    private javax.swing.JTextField CustomerIDtxt;
    private javax.swing.JLabel CustomerInfolabel;
    private javax.swing.JLabel CustomerNamelabel;
    private javax.swing.JTextField CustomerNametxt;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JPanel FrontPanel;
    private javax.swing.JLabel GoldLabel;
    private javax.swing.JTextField GoldTxt;
    private javax.swing.JTextField MobileNoTxt;
    private javax.swing.JLabel MobileNolabel;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductIDTxt;
    private javax.swing.JLabel ProductInfoLabel;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTxt;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTxt1;
    private javax.swing.JButton SearchBut;
    private javax.swing.JButton SellButton;
    private javax.swing.JLabel StoneLabel;
    private javax.swing.JTextField StoneTxt;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JTextField TransIDTxt;
    private javax.swing.JLabel TransIdLabel;
    private javax.swing.JLabel VatLabel;
    private javax.swing.JTextField VatTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    double gold;
    double stone;
    double charge;
    double vat;
    double total;
    Image image;
    File f;
    // End of variables declaration                   
}
